### ISSUE TITLE
Non-English word count is wrong (possibly)

### ISSUE THREAD

**Issue by mrNo0b** [getgrav/grav-plugin-readingtime#11]
I have Hebrew text on my page, after debugging this line (ln 36 in classes/TwigReadingTimeFilters.php)
`$words = str_word_count(strip_tags($content));`
I found out that when I remove the strip_tags method it will give differnt (much more realistic) word count
so for one of the pages I tested it on I had:
12 - with strip_tags()
126 - without strip_tags()
I don't know if there is something wrong with my site language setup or something, 
but maybe you can check the plugin...
if you need, here is a [Hebrew Lorem Ispum text](http://www.lorem-ipsum.co.il/lorem-ipsum.php)

btw, here is the Hebrew translation strings:
```
he:
  PLUGIN_READINGTIME:
    SECOND: שניה
    SECONDS: שניות
    MINUTE: דקה
    MINUTES: דקות
```
