### ISSUE TITLE
Add nl language

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-plugin-readingtime#13]
Excuse my unfamiliarity with Git.
May I suggest adding a Dutch translation to (languages.yaml)
```
nl:
  PLUGIN_READINGTIME:
    SECOND: seconde
    SECONDS: seconden
    MINUTE: minuut
    MINUTES: minuten
```
This does not seem to work:
`{{ page.content|readingtime({'minutes_label': 'minuten', 'minute_label': 'minuut', 'seconds_label': 'seconden', 'second_label': 'seconde'}) }}`
