### ISSUE TITLE
Labels don't update

### ISSUE THREAD

**Issue by woutertoday** [getgrav/grav-plugin-readingtime#9]
`page.content|readingtime({ 'minute_label': 'minuut' })`

Does not work. Adding all of the labels also doesn't work. I've tried changing/adding to the `languages.yaml` file, but nothing seems to work.

**Comment by francescomugnai** [comment]
I've the same issue

**Comment by Blazeflack** [comment]
I came here with the same issue and noticed this ticket.

**Comment by mrNo0b** [comment]
You can add those 4 string to your languages.yaml file inside theme folder,
but make sure you have same spaces structure as the plugin structure has.
so for example to the end of language English strings group you:
```
en:
  ... langauge strings...
  PLUGIN_READINGTIME:
    SECOND: second
    SECONDS: seconds
    MINUTE: minute
    MINUTES: minutes
```
worked for me...
